require 'rspec'
require './lib/string_expansion'

RSpec.describe 'String Expansion' do
  it 'takes string, expands it based on values inside string' do
    expect(string_expansion("3M2u5b2a1s1h2i1r")).to eq("MMMuubbbbbaashiir")
    expect(string_expansion("3Mat")).to eq("MMMaaattt")
    expect(string_expansion("3M123u42b12a")).to eq("MMMuuubbaa")
    expect(string_expansion("3n6s7f3n")).to eq("nnnssssssfffffffnnn")
    expect(string_expansion("0d4n8d2b")).to eq("nnnnddddddddbb")
    expect(string_expansion("0c3b1n7m")).to eq("bbbnmmmmmmm")
    expect(string_expansion("7m3j4ik2a")).to eq("mmmmmmmjjjiiiikkkkaa")
    expect(string_expansion("3A5m3B3Y")).to eq("AAAmmmmmBBBYYY")
    expect(string_expansion("5M0L8P1")).to eq("MMMMMPPPPPPPP")
    expect(string_expansion("2B")).to eq("BB")
    expect(string_expansion("7M1n3K")).to eq("MMMMMMMnKKK")
    expect(string_expansion("A4g1b4d")).to eq("Aggggbdddd")
    expect(string_expansion("111111")).to eq("")
    expect(string_expansion("4d324n2")).to eq("ddddnnnn")
    expect(string_expansion("5919nf3u")).to eq("nnnnnnnnnfffffffffuuu")
    expect(string_expansion("2n1k523n4i")).to eq("nnknnniiii")
    expect(string_expansion("6o23M32d")).to eq("ooooooMMMdd")
    expect(string_expansion("1B44n3r")).to eq("Bnnnnrrr")
    expect(string_expansion("M21d1r32")).to eq("Mdr")
    expect(string_expansion("23M31r2r2")).to eq("MMMrrr")
    expect(string_expansion("8494mM25K2A")).to eq("mmmmMMMMKKKKKAA")
    expect(string_expansion("4A46D6B3C")).to eq("AAAADDDDDDBBBBBBCCC")
    expect(string_expansion("23D42B3A")).to eq("DDDBBAAA")
    expect(string_expansion("143D36C1A")).to eq("DDDCCCCCCA")
    expect(string_expansion("asdf")).to eq("asdf")
    expect(string_expansion("23jbjl1eb")).to eq("jjjbbbjjjllleb")
    expect(string_expansion("43ibadsr3")).to eq("iiibbbaaadddsssrrr")
    expect(string_expansion("123p9cdbjs")).to eq("pppcccccccccdddddddddbbbbbbbbbjjjjjjjjjsssssssss")
    expect(string_expansion("2309ew7eh")).to eq("eeeeeeeeewwwwwwwwweeeeeeehhhhhhh")
    expect(string_expansion("312987rfebd")).to eq("rrrrrrrfffffffeeeeeeebbbbbbbddddddd")
    expect(string_expansion("126cgec")).to eq("ccccccggggggeeeeeecccccc")
    expect(string_expansion("1chwq3rfb")).to eq("chwqrrrfffbbb")
    expect(string_expansion("389fg21c")).to eq("fffffffffgggggggggc")
    expect(string_expansion("239vbsac")).to eq("vvvvvvvvvbbbbbbbbbsssssssssaaaaaaaaaccccccccc")
    expect(string_expansion("davhb327vuc")).to eq("davhbvvvvvvvuuuuuuuccccccc")
    expect(string_expansion("cvyb239bved2dv")).to eq("cvybbbbbbbbbbvvvvvvvvveeeeeeeeedddddddddddvv")
    expect(string_expansion("")).to eq("")
  end
end